
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "no-cache"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
