[build]
  publish = "public"

# Allow sitemap.xml and robots.txt to be served correctly
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

# This catch-all should come LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Add correct content type for sitemap.xml
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "no-cache"
